version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    # working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:  go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
   docker:
      - image: ubuntu:latest
   steps:
     - checkout
     - run:
         name: build push image karsajobs
         command: ./build_push_image_karsajobs.sh

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app