version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  build-app-karsajobs-ui:
   docker:
      - image: docker:stable
   steps:
     - checkout
     - setup_remote_docker
     - run: docker build -t ghcr.io/airellrmdn/karsajobs-ui:latest .
     - run: echo $PASSWORD_GHCR | docker login ghcr.io --username airellrmdn --password-stdin
     - run: docker push ghcr.io/airellrmdn/karsajobs-ui:latest

# Orchestrate our job run sequence
workflows:
  build_push:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile